[package]
version = "1.0.0"
authors = ["NVIDIA"]
title = "Omni.UI Scene Object Info Example"
description = "This example show an 3d info pophover type tool tip scene object"
readme = "docs/README.md"
repository = "https://gitlab-master.nvidia.com/omniverse/kit-extensions/kit-scene"
category = "Documentation"
keywords = ["ui", "example", "scene", "docs", "documentation", "popover"]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.ui.scene" = {  }
"omni.usd" = {  }
"omni.kit.viewport.utility" = {  }

[[python.module]]
name = "omni.example.ui.scene.object_info"

[[test]]
args = ["--/renderer/enabled=pxr", "--/renderer/active=pxr", "--no-window"]
dependencies = ["omni.hydra.pxr", "omni.kit.window.viewport"]
