[package]
version = "1.1.1"
authors = ["NVIDIA"]
title = "Omni.UI Scene Sample For Manipulating Select Light"
description = "This example show an 3D manipulator for a selected light"
readme = "docs/README.md"
repository = "https://gitlab-master.nvidia.com/omniverse/kit-extensions/kit-scene"
category = "Documentation"
keywords = ["ui", "example", "scene", "docs", "documentation", "light"]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.ui.scene" = {  }
"omni.usd" = {  }
"omni.kit.viewport.utility" = {  }
"omni.kit.commands" = { }

[[python.module]]
name = "omni.example.ui_scene.light_manipulator"

[[test]]
args = [
    "--/renderer/enabled=pxr",
    "--/renderer/active=pxr",
    "--/app/viewport/forceHideFps=true",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--no-window"
]
dependencies = [
    "omni.hydra.pxr",
    "omni.kit.test_helpers_gfx",
    "omni.kit.viewport.utility",
    "omni.kit.window.viewport"
]
