[package]
version = "1.2.1"
authors = ["Victor Yudin <vyudin@nvidia.com>"]
title = "Omni.UI Scene Slider Example"
description="The interactive example of the slider manipulator with omni.ui.scene"
readme  = "docs/README.md"
repository="https://gitlab-master.nvidia.com/omniverse/kit-extensions/kit-scene"
category = "Documentation"
keywords = ["ui", "example", "scene", "docs", "documentation", "slider"]
changelog="docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.manipulator.viewport" = {}
"omni.kit.viewport.registry" = {}
"omni.ui.scene" = {}
"omni.usd" = {}

[[python.module]]
name = "omni.example.ui_scene.slider_manipulator"
