[package]
version = "1.0.1"
authors = ["NVIDIA"]
title = "Omni.UI Scene Object Info with Widget Example"
description = "This example show an 3d info pophover type tool tip scene object"
readme = "docs/README.md"
repository = "https://gitlab-master.nvidia.com/omniverse/kit-extensions/kit-scene"
category = "Documentation"
keywords = ["ui", "example", "scene", "docs", "documentation", "popover"]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.viewport.utility" = {  }
"omni.ui.scene" = {  }
"omni.usd" = {  }

[[python.module]]
name = "omni.example.ui_scene.widget_info"

[[test]]
args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--no-window"
]
dependencies = [
    "omni.kit.renderer.core",
    "omni.kit.renderer.capture",
]
